//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : EditorInterface
//  @ File Name : qogrewidget.h
//  @ Date : 10.03.2013
//  @ Author : Sergei Forrest
//
//

#if !defined(_QOGREWIDGET_H)
#define _QOGREWIDGET_H

#include <QtOpenGL/QGLWidget>
#include <Ogre.h>

namespace QtOgre
{
	class QOgreWidget : public QGLWidget
    {
        Q_OBJECT

	public:
        QOgreWidget(Ogre::Root* ogreRoot);
        ~QOgreWidget();
		Ogre::RenderWindow* getOgreWindow();

    protected:
		virtual void paintEvent(QPaintEvent* pEvent);
		virtual void resizeEvent(QResizeEvent* rEvent);
		virtual void update();

    private:
		Ogre::RenderWindow* ogreRenderWindow;
		Ogre::Root* ogreRoot;
	};
}

#endif  //_QOGREWIDGET_H
